/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RiskLevel = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const SuspiciousSentence = IDL.Record({
  'sentence' : IDL.Text,
  'confidence' : IDL.Nat,
  'riskLevel' : RiskLevel,
});
export const Citation = IDL.Record({
  'citationText' : IDL.Text,
  'explanation' : IDL.Text,
  'isFake' : IDL.Bool,
});
export const AnalysisResult = IDL.Record({
  'suspiciousSentences' : IDL.Vec(SuspiciousSentence),
  'trustScore' : IDL.Nat,
  'overallConfidence' : IDL.Nat,
  'analysisExplanation' : IDL.Text,
  'citations' : IDL.Vec(Citation),
  'riskLevel' : RiskLevel,
});
export const AnalysisResponse = IDL.Variant({
  'ok' : AnalysisResult,
  'err' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'analyzeForHallucination' : IDL.Func([IDL.Text], [AnalysisResponse], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RiskLevel = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const SuspiciousSentence = IDL.Record({
    'sentence' : IDL.Text,
    'confidence' : IDL.Nat,
    'riskLevel' : RiskLevel,
  });
  const Citation = IDL.Record({
    'citationText' : IDL.Text,
    'explanation' : IDL.Text,
    'isFake' : IDL.Bool,
  });
  const AnalysisResult = IDL.Record({
    'suspiciousSentences' : IDL.Vec(SuspiciousSentence),
    'trustScore' : IDL.Nat,
    'overallConfidence' : IDL.Nat,
    'analysisExplanation' : IDL.Text,
    'citations' : IDL.Vec(Citation),
    'riskLevel' : RiskLevel,
  });
  const AnalysisResponse = IDL.Variant({
    'ok' : AnalysisResult,
    'err' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'analyzeForHallucination' : IDL.Func([IDL.Text], [AnalysisResponse], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };