/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type AnalysisResponse = {
    __kind__: "ok";
    ok: AnalysisResult;
} | {
    __kind__: "err";
    err: string;
};
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Citation {
    citationText: string;
    explanation: string;
    isFake: boolean;
}
export interface SuspiciousSentence {
    sentence: string;
    confidence: bigint;
    riskLevel: RiskLevel;
}
export interface AnalysisResult {
    suspiciousSentences: Array<SuspiciousSentence>;
    trustScore: bigint;
    overallConfidence: bigint;
    analysisExplanation: string;
    citations: Array<Citation>;
    riskLevel: RiskLevel;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum RiskLevel {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export interface backendInterface {
    analyzeForHallucination(text: string): Promise<AnalysisResponse>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AnalysisResponse as _AnalysisResponse, AnalysisResult as _AnalysisResult, Citation as _Citation, RiskLevel as _RiskLevel, SuspiciousSentence as _SuspiciousSentence } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async analyzeForHallucination(arg0: string): Promise<AnalysisResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeForHallucination(arg0);
                return from_candid_AnalysisResponse_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeForHallucination(arg0);
            return from_candid_AnalysisResponse_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_AnalysisResponse_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisResponse): AnalysisResponse {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_AnalysisResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisResult): AnalysisResult {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SuspiciousSentence_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SuspiciousSentence): SuspiciousSentence {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suspiciousSentences: Array<_SuspiciousSentence>;
    trustScore: bigint;
    overallConfidence: bigint;
    analysisExplanation: string;
    citations: Array<_Citation>;
    riskLevel: _RiskLevel;
}): {
    suspiciousSentences: Array<SuspiciousSentence>;
    trustScore: bigint;
    overallConfidence: bigint;
    analysisExplanation: string;
    citations: Array<Citation>;
    riskLevel: RiskLevel;
} {
    return {
        suspiciousSentences: from_candid_vec_n5(_uploadFile, _downloadFile, value.suspiciousSentences),
        trustScore: value.trustScore,
        overallConfidence: value.overallConfidence,
        analysisExplanation: value.analysisExplanation,
        citations: value.citations,
        riskLevel: from_candid_RiskLevel_n8(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sentence: string;
    confidence: bigint;
    riskLevel: _RiskLevel;
}): {
    sentence: string;
    confidence: bigint;
    riskLevel: RiskLevel;
} {
    return {
        sentence: value.sentence,
        confidence: value.confidence,
        riskLevel: from_candid_RiskLevel_n8(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AnalysisResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AnalysisResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AnalysisResult_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): RiskLevel {
    return "Low" in value ? RiskLevel.Low : "High" in value ? RiskLevel.High : "Medium" in value ? RiskLevel.Medium : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SuspiciousSentence>): Array<SuspiciousSentence> {
    return value.map((x)=>from_candid_SuspiciousSentence_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
